run_mode: FULL_RUN # FULL_RUN | RESUME | POST_PROCESS_ONLY

benchmark_dir: benchmarks/PRA2017/large
ins_index_source: benchmarks/PRA2017/pra2017_hybrid_match.csv
ins_index: [ 0, 1, 2, 3 ]
bks_table_csv_path: benchmarks/PRA2017/pra2017_bks_table.csv

output_dir: output/20260502

instance_worker_cnt: 96

draw_gantt: true
painter_thread_cnt: 48

scenarios:
  - name: end_time
    timelimit: 300.0
    output_subdir: end_time
    subroutine_flow:
      - method: apply_lb_by_mcf
        draw_heatmap: true
        heatmap_sort: "end_time"
      - method: single_pass_last_stage_only_sch_from_mcf_lb
        job_priority: "end_time"
        placement_priority: "dist"
        pf_method: "PF1"
        solver_thread_cnt: 1
        total_tl: 0.01nc
        log_cp_search_progress: true

  - name: start_time_maxw
    timelimit: 300.0
    output_subdir: start_time_maxw
    subroutine_flow:
      - method: apply_lb_by_mcf
        draw_heatmap: true
        heatmap_sort: "start_time_maxw"
      - method: single_pass_last_stage_only_sch_from_mcf_lb
        job_priority: "start_time_maxw"
        placement_priority: "dist"
        pf_method: "PF1"
        solver_thread_cnt: 1
        total_tl: 0.01nc
        log_cp_search_progress: true

  - name: end_time_maxw
    timelimit: 300.0
    output_subdir: end_time_maxw
    subroutine_flow:
      - method: apply_lb_by_mcf
        draw_heatmap: true
        heatmap_sort: "end_time_maxw"
      - method: single_pass_last_stage_only_sch_from_mcf_lb
        job_priority: "end_time_maxw"
        placement_priority: "dist"
        pf_method: "PF1"
        solver_thread_cnt: 1
        total_tl: 0.01nc
        log_cp_search_progress: true
